# Generated by Django 5.0.4 on 2024-04-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField(verbose_name='время начала рассылки')),
                ('datetime_finish', models.DateTimeField(verbose_name='время окончания рассылки')),
                ('period', models.CharField(choices=[('ONCE', 'Единоразовая'), ('DAILY', 'Раз в день'), ('WEEKLY', 'Раз в неделю'), ('MONTHLY', 'Раз в месяц')], default='DAILY', max_length=25, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('STARTED', 'Запущена'), ('FINISHED', 'Завершена')], default='CREATED', max_length=25, verbose_name='статус рассылки')),
                ('clients', models.ManyToManyField(to='client.client', verbose_name='клиенты')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.message', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('try_time', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('try_status', models.CharField(max_length=50, verbose_name='статус попытки')),
                ('server_answer', models.CharField(blank=True, max_length=250, null=True, verbose_name='ответ почтового сервера')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='клиенты')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
